-- 아이디,비밀번호 VEF로 커넥션 생성
-- SYSTEM 계정에서 아래와 같이 유저 생성
--CREATE USER VEF IDENTIFIED by VEF;
--GRANT RESOURCE, CONNECT TO VEF;

==================== MEMBER 테이블 ====================

CREATE TABLE MEMBER (
    USER_NUM NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(30) NOT NULL UNIQUE,
    USER_PWD VARCHAR2(100) NOT NULL,
    USER_EMAIL VARCHAR2(100) NOT NULL,
    USER_NAME VARCHAR2(15) NOT NULL,
    ENROLL_DATE DATE DEFAULT SYSDATE,
    VEG_TYPE VARCHAR2(30) NOT NULL,
    USER_ROLE VARCHAR2(10) DEFAULT 'ROLE_USER',
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN ('Y','N'))
);

COMMENT ON COLUMN MEMBER.USER_NUM IS '회원번호';
COMMENT ON COLUMN MEMBER.USER_ID IS '아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.USER_EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.USER_NAME IS '닉네임';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '가입일시';
COMMENT ON COLUMN MEMBER.VEG_TYPE IS '선호';
COMMENT ON COLUMN MEMBER.USER_ROLE IS '권한';
COMMENT ON COLUMN MEMBER.STATUS IS '상태';

CREATE SEQUENCE SEQ_USER_NUM;

INSERT INTO MEMBER VALUES(
SEQ_USER_NUM.NEXTVAL,
'admin',
'1234',
'admin@vef.com',
'관리자',
SYSDATE,
'비건',
'ROLE_ADMIN',
DEFAULT
);

INSERT INTO MEMBER VALUES(
SEQ_USER_NUM.NEXTVAL,
'spark',
'1234',
'372dev@gmail.com',
'372',
SYSDATE,
'플렉시테리언',
DEFAULT,
DEFAULT
);

COMMIT;