
-- QnA 질문 테이블 생성
CREATE TABLE QnA_MEMBER (
    Que_Num NUMBER,
    User_Num NUMBER NOT NULL UNIQUE,
    Que_Title VARCHAR2(100) NOT NULL,
    Que_Content VARCHAR2(500) NOT NULL,
    Que_Date DATE DEFAULT SYSDATE,
    HIT NUMBER(4) DEFAULT 0,
    QGROUP NUMBER(4),
    STEP NUMBER(4),
    QINDENT NUMBER (4)
);

COMMENT ON COLUMN QnA_MEMBER.Que_Num IS '문의번호';
COMMENT ON COLUMN QnA_MEMBER.User_Num IS '회원번호';
COMMENT ON COLUMN QnA_MEMBER.Que_Title IS '문의제목';
COMMENT ON COLUMN QnA_MEMBER.Que_Content IS '문의내용';
COMMENT ON COLUMN QnA_MEMBER.Que_Date IS '문의날짜';
COMMENT ON COLUMN QnA_MEMBER.HIT IS '조회수';
COMMENT ON COLUMN QnA_MEMBER.QGROUP IS '답변';
COMMENT ON COLUMN QnA_MEMBER.STEP IS 'N번째 떨어진 글';
COMMENT ON COLUMN QnA_MEMBER.QINDENT IS 'N번 들여쓰기한 글';

CREATE SEQUENCE SEQ_QnA_MEMBER_NO;

SELECT *
FROM QNA_MEMBER;

SELECT Que_Num, User_Num, Que_Title, Que_Content, Que_Date, HIT, QGROUP, STEP, QINDENT
FROM QNA_MEMBER;

SELECT COUNT(*) FROM QNA_MEMBER;

-- INSERT INTO QNA_MEMBER VALUES(SEQ_QnA_MEMBER_NO.NEXTVAL, 2, '문의제목', '문의내용', DEFAULT, 2, 3, 4, 5);

INSERT INTO QNA_MEMBER VALUES(SEQ_QnA_MEMBER_NO.NEXTVAL, ?, ?, ?, DEFAULT, DEFAULT, SEQ_QNA_MEMBER_NO.CURRVAL, ?, ?);

--INSERT INTO QNA_MEMBER VALUES(SEQ_QnA_MEMBER_NO.NEXTVAL, 2, '문의제목', '문의내용', DEFAULT, 2, SEQ_QNA_MEMBER_NO.CURRVAL, 0, 0);












-- UPDATE QnA_MEMBER SET Que_Title='제목1212', Que_Content='내용1212' WHERE USER_NUM=2;

UPDATE QnA_MEMBER SET Que_Title=?, Que_Content=? WHERE USER_NUM=?;

COMMIT;



















