
-- QnA 질문 테이블 생성
CREATE TABLE QnA_MEMBER (
    Que_Num NUMBER,
    User_Num NUMBER NOT NULL,
    Que_Title VARCHAR2(100) NOT NULL,
    Que_Content VARCHAR2(500) NOT NULL,
    Que_Date DATE DEFAULT SYSDATE,
    HIT NUMBER(4) DEFAULT 0,
    QGROUP NUMBER(4),
    STEP NUMBER(4),
    QINDENT NUMBER (4)
);

COMMENT ON COLUMN QnA_MEMBER.Que_Num IS '문의번호';
COMMENT ON COLUMN QnA_MEMBER.User_Num IS '회원번호';
COMMENT ON COLUMN QnA_MEMBER.Que_Title IS '문의제목';
COMMENT ON COLUMN QnA_MEMBER.Que_Content IS '문의내용';
COMMENT ON COLUMN QnA_MEMBER.Que_Date IS '문의날짜';
COMMENT ON COLUMN QnA_MEMBER.HIT IS '조회수';
COMMENT ON COLUMN QnA_MEMBER.QGROUP IS '그룹번호';
COMMENT ON COLUMN QnA_MEMBER.STEP IS 'N번째 떨어진 글';
COMMENT ON COLUMN QnA_MEMBER.QINDENT IS 'N번 들여쓰기한 글';

CREATE SEQUENCE SEQ_QnA_MEMBER_NO;

SELECT *
FROM QNA_MEMBER;

SELECT Que_Num, User_Num, Que_Title, Que_Content, Que_Date, HIT, QGROUP, STEP, QINDENT
FROM QNA_MEMBER;

SELECT Que_Num, User_Num, Que_Title, Que_Content, Que_Date, HIT, QGROUP, STEP, QINDENT
FROM QNA_MEMBER
ORDER BY QGROUP DESC, STEP ASC;

SELECT COUNT(*) FROM QNA_MEMBER;

-- INSERT INTO QNA_MEMBER VALUES(SEQ_QnA_MEMBER_NO.NEXTVAL, 2, '문의제목', '문의내용', DEFAULT, 2, 3, 4, 5);

INSERT INTO QNA_MEMBER VALUES(SEQ_QnA_MEMBER_NO.NEXTVAL, ?, ?, ?, DEFAULT, DEFAULT, SEQ_QNA_MEMBER_NO.CURRVAL, ?, ?);

--INSERT INTO QNA_MEMBER VALUES(SEQ_QnA_MEMBER_NO.NEXTVAL, 2, '문의제목', '문의내용', DEFAULT, 2, SEQ_QNA_MEMBER_NO.CURRVAL, 0, 0);



SELECT Que_Num, User_Num, Que_Title, Que_Content, Que_Date, HIT, QGROUP, STEP, QINDENT FROM QNA_MEMBER;

SELECT Que_Num, User_Num, Que_Title, Que_Content, Que_Date, HIT, QGROUP, STEP, QINDENT FROM QNA_MEMBER WHERE RNUM BETWEEN 1 AND 10;

SELECT Que_Num, User_Num, Que_Title, Que_Content, Que_Date, HIT, QGROUP, STEP, QINDENT
FROM QNA_MEMBER;






-- UPDATE QnA_MEMBER SET Que_Title='제목1212', Que_Content='내용1212' WHERE USER_NUM=2;

UPDATE QnA_MEMBER SET Que_Title=?, Que_Content=? WHERE USER_NUM=?;

COMMIT;

UPDATE QnA_MEMBER SET HIT=? WHERE Que_Num=?;

COMMIT;

UPDATE QnA_MEMBER SET Que_Title=?, Que_Content=?, QGROUP=?, STEP=?, QINDENT=? WHERE USER_NUM=?;




-- 공지사항 테이블 생성
CREATE TABLE NOTICE (
    NNUM NUMBER,
    User_Num NUMBER NOT NULL,
    NTITLE VARCHAR2(100) NOT NULL,
    NCONTENT VARCHAR2(500) NOT NULL,
    NDATE DATE DEFAULT SYSDATE,
    NHIT NUMBER(4) DEFAULT 0
);

COMMENT ON COLUMN NOTICE.NNUM IS '공지번호';
COMMENT ON COLUMN NOTICE.User_Num IS '회원번호';
COMMENT ON COLUMN NOTICE.NTITLE IS '공지제목';
COMMENT ON COLUMN NOTICE.NCONTENT IS '공지내용';
COMMENT ON COLUMN NOTICE.NDATE IS '공지날짜';
COMMENT ON COLUMN NOTICE.NHIT IS '조회수';


CREATE SEQUENCE SEQ_NOTICE_NO;

SELECT NNUM, User_Num, NTITLE, NCONTENT, NDATE, NHIT
FROM NOTICE;

SELECT COUNT(*)
FROM NOTICE;

INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.nextval, ?, ?, ?, DEFAULT, DEFAULT);

UPDATE NOTICE SET NTITLE=?, NCONTENT=? WHERE User_Num=?;

SELECT NNUM, User_Num, NTITLE, NCONTENT, NDATE, NHIT FROM NOTICE WHERE User_Num =?;

UPDATE NOTICE SET NHIT=? WHERE User_Num=?;



INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.nextval, 1, '공지제목', '공지내용', DEFAULT, DEFAULT);




----------------- MEMBER 테이블 -----------------

CREATE TABLE MEMBER (
USER_NUM NUMBER PRIMARY KEY,
USER_ID VARCHAR2(30) NOT NULL UNIQUE,
USER_PWD VARCHAR2(100) NOT NULL,
USER_EMAIL VARCHAR2(100) NOT NULL,
ENROLL_DATE DATE DEFAULT SYSDATE,
VEG_TYPE VARCHAR2(30) NOT NULL,
USER_ROLE VARCHAR2(10) DEFAULT 'ROLE_USER',
STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN ('Y','N')),
SALT VARCHAR2(256)
);

COMMENT ON COLUMN MEMBER.USER_NUM IS '회원번호';
COMMENT ON COLUMN MEMBER.USER_ID IS '아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.USER_EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '가입일시';
COMMENT ON COLUMN MEMBER.VEG_TYPE IS '선호';
COMMENT ON COLUMN MEMBER.USER_ROLE IS '권한';
COMMENT ON COLUMN MEMBER.STATUS IS '상태';

CREATE SEQUENCE SEQ_USER_NUM;

INSERT INTO MEMBER VALUES(
SEQ_USER_NUM.NEXTVAL,
'admin',
'Zhinpmbw7t/qst0TgqsF+6a3W7xVH1kXvikP6H4/sDk=',
'1234@test.com',
SYSDATE,
'v1',
'ROLE_ADMIN',
DEFAULT,
'2b32f727aaf8cf17'
);

COMMIT;



rollback;




















