CREATE TABLE MEMBER (
    USER_NUM NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(30) NOT NULL UNIQUE,
    USER_PWD VARCHAR2(100) NOT NULL,
    USER_EMAIL VARCHAR2(100) NOT NULL,
    USER_NAME VARCHAR2(15) NOT NULL,
    ENROLL_DATE DATE DEFAULT SYSDATE,
    VEG_TYPE VARCHAR2(30) NOT NULL,
    USER_ROLE VARCHAR2(10) DEFAULT 'ROLE_USER',
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN ('Y','N'))
);

COMMENT ON COLUMN MEMBER.USER_NUM IS '회원번호';
COMMENT ON COLUMN MEMBER.USER_ID IS '아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.USER_EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.USER_NAME IS '닉네임';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '가입일시';
COMMENT ON COLUMN MEMBER.VEG_TYPE IS '선호';
COMMENT ON COLUMN MEMBER.USER_ROLE IS '권한';
COMMENT ON COLUMN MEMBER.STATUS IS '상태';

CREATE SEQUENCE SEQ_USER_NUM;

INSERT INTO MEMBER VALUES(
SEQ_USER_NUM.NEXTVAL,
'admin',
'1234',
'admin@vef.com',
'관리자',
SYSDATE,
'비건',
'ROLE_ADMIN',
DEFAULT
);

INSERT INTO MEMBER VALUES(
SEQ_USER_NUM.NEXTVAL,
'spark',
'1234',
'372dev@gmail.com',
'372',
SYSDATE,
'플렉시테리언',
DEFAULT,
DEFAULT
);

COMMIT;



---------------

CREATE TABLE BOARD (	
    "BOARD_NO" NUMBER,
	"BOARD_TITLE" VARCHAR2(50), 
	"BOARD_CONTENT" VARCHAR2(2000), 
	"BOARD_IMAGEF_FILE" VARCHAR2(100), 
    "BOARD_CREATE_DATE" DATE DEFAULT SYSDATE, 
    "BOARD_MODIFY_DATE" DATE DEFAULT SYSDATE,
    "VEGANLIST" VARCHAR2(50),
    "SITUATION" VARCHAR2(50),
    "BOARD_READCOUNT" NUMBER DEFAULT 0, 
    "STATUS" VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    "IMAGE_FILE1" VARCHAR(100), 
    "IMAGE_FILE2" VARCHAR(100), 
    "IMAGE_FILE3" VARCHAR(100), 
    CONSTRAINT PK_BOARD_NO PRIMARY KEY(BOARD_NO)
);

CREATE SEQUENCE SEQ_BOARD_NO;

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글번호';
COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글제목';
COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글내용';
COMMENT ON COLUMN "BOARD"."BOARD_IMAGEF_FILE" IS '이미지파일';
COMMENT ON COLUMN "BOARD"."BOARD_CREATE_DATE" IS '게시글올린날짜';
COMMENT ON COLUMN "BOARD"."BOARD_DATEMODIFY_DATE" IS '게시글수정날짜';
COMMENT ON COLUMN "BOARD"."VEGANLIST" IS '비건종류';
COMMENT ON COLUMN "BOARD"."SITUATION" IS '상황종류';
COMMENT ON COLUMN "BOARD"."BOARD_READCOUNT" IS '조회수';
COMMENT ON COLUMN "BOARD"."STATUS" IS '상태값(Y/N)';
COMMENT ON COLUMN "BOARD"."VEGANLIST" IS '비건종류';
COMMENT ON COLUMN "BOARD"."IMAGE_FILE1" IS '완성사진1';
COMMENT ON COLUMN "BOARD"."IMAGE_FILE2" IS '완성사진2';
COMMENT ON COLUMN "BOARD"."IMAGE_FILE3" IS '완성사진3';


--댓글
CREATE TABLE REPLY(
  REPLY_NO NUMBER PRIMARY KEY,
  BOARD_NO NUMBER,
  REPLY_CONTENT VARCHAR2(400),
  REPLY_CREATE_DATE DATE,
  FOREIGN KEY (BOARD_NO) REFERENCES BOARD
);

CREATE SEQUENCE SEQ_REPLY_NO;

COMMENT ON COLUMN "REPLY"."REPLY_NO" IS '댓글번호';
COMMENT ON COLUMN "REPLY"."BOARD_NO" IS '댓글이작성된게시글';
COMMENT ON COLUMN "REPLY"."REPLY_CONTENT" IS '댓글내용';
COMMENT ON COLUMN "REPLY"."REPLY_CREATE_DATE" IS '댓글올린날짜';



ALTER TABLE REPLY ADD REPLY_WRITER_NO NUMBER;
ALTER TABLE REPLY ADD CONSTRAINT MEMBER FOREIGN KEY (REPLY_WRITER_NO) REFERENCES MEMBER;
ALTER TABLE REPLY ADD STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'));
ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_WRITER FOREIGN KEY(BOARD_WRITER_NO) REFERENCES MEMBER(USER_NUM) ON DELETE SET NULL;
ALTER TABLE BOARD ADD "BOARD_WRITER_NO" NUMBER;

ALTER TABLE BOARD ADD "RECOMMEND" NUMBER DEFAULT 0;


COMMIT;